M48
; DRILL file {KiCad 7.0.7} date sáb 04 nov 2023 12:16:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-04T12:16:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X101.3Y-107.6
T2
X112.9Y-103.14
X112.9Y-109.66
T0
M30
